include:
  - .well-known
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  - /join
  - /join/

# MIMEタイプの設定
mime_types:
  .well-known/apple-app-site-association: application/json 